### ISSUE TITLE
Setup basic layout

### ISSUE THREAD

**Issue by cheezeypotatoes** [fee-slc-2017/Group-Project-One#7]
*hash out basic wireframe layout of site using css/flexbox

**Comment by cheezeypotatoes** [comment]
this is a duplicate of #1, closing #1 and working this issue.

**Comment by T-dex** [comment]
@cheezeypotatoes  @CaptRat working on wireframing

**Comment by johnsonr84** [comment]
Q - Team Beta what are you planning for your wire frame concept? Team Alpha (aka Rob, Tyler and Josh) would like to create a similar concept as the last FE cohort displaying our individual profiles so that we may direct potential employers to our individual portfolio containing some samples of our devs. In this instance we would most likely need at least 7 total cards on the homepage for our profile photos.

**Comment by T-dex** [comment]
Who the hell decided you were team Alpha? We are supermegaawesomegoldteamgoBravo! (kidding)

We are working on building the basic wireframing with float properties on the CSS

**Comment by T-dex** [comment]
I will fill them in on the 7 cards idea

**Comment by johnsonr84** [comment]
Here is the link to the previous cohorts group project. I think we can come up with something much more visually pleasing and organized. [https://fee-slc-2016.github.io/tiy-slc-fee-2016/#myCarousel](url)

**Comment by johnsonr84** [comment]
We dig the simplicity of the apple website [http://www.apple.com/](url)
Also we think we should attempt to have a nice group photo of our team located where the watches are in the website. Thoughts?

**Comment by T-dex** [comment]
Don't think we are quiet there but I like the idea

**Comment by T-dex** [comment]
Done Curt- layout
